framework:
    cache:
        # Redis
        app: cache.adapter.redis
        default_redis_provider: '%env(string:REDIS_DSN)%'

        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cache: null
