parameters:
    api.url.main: "%env(string:MAIN_API_URL)%"
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Connectors\Article\ArticleHttpClient:
        arguments:
            $apiUrl: '%api.url.main%'
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'

    App\Connectors\Author\AuthorHttpClient:
        arguments:
            $apiUrl: '%api.url.main%'
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'

    App\Service\Article\ArticleProxyCacheAdapter: ~
    App\Service\Article\ArticleProxyServiceInterface: '@App\Service\Article\ArticleProxyCacheAdapter'

    App\Service\Author\AuthorProxyCacheAdapter: ~
    App\Service\Author\AuthorProxyServiceInterface: '@App\Service\Author\AuthorProxyCacheAdapter'